import { Patient, Consultation } from './types';

export const mockPatients: Patient[] = [
  {
    id: 'pat-001',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '123-456-7890',
    dob: '1985-05-20',
    patientHistory: 'No major illnesses. Allergic to penicillin.',
    dentalChart: 'All teeth present. Minor plaque buildup on lower incisors.',
  },
  {
    id: 'pat-002',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '234-567-8901',
    dob: '1992-08-15',
    patientHistory: 'History of migraines. Non-smoker.',
    dentalChart: 'Wisdom teeth extracted in 2015. Crown on upper right molar.',
  },
  {
    id: 'pat-003',
    name: 'Michael Johnson',
    email: 'michael.j@example.com',
    phone: '345-678-9012',
    dob: '1978-11-30',
    patientHistory: 'High blood pressure, managed with medication.',
    dentalChart: 'Requires root canal on lower left molar.',
  },
  {
    id: 'pat-004',
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    phone: '456-789-0123',
    dob: '2001-02-10',
    patientHistory: 'None.',
    dentalChart: 'Excellent oral hygiene. Scheduled for routine cleaning.',
  },
  {
    id: 'pat-005',
    name: 'David Wilson',
    email: 'david.wilson@example.com',
    phone: '567-890-1234',
    dob: '1995-07-22',
    patientHistory: 'Asthma, uses inhaler as needed.',
    dentalChart: 'Noticeable coffee stains. Interested in whitening options.',
  },
];

export const mockConsultations: Consultation[] = [
  {
    id: 'con-001',
    patientId: 'pat-001',
    date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString().split('T')[0],
    time: '10:00',
    reason: 'Routine Check-up & Cleaning',
    price: 75,
    status: 'Scheduled',
    treatmentPlan: 'Standard cleaning and polishing.',
    followUpActions: 'Schedule next 6-month check-up.',
  },
  {
    id: 'con-002',
    patientId: 'pat-002',
    date: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString().split('T')[0],
    time: '14:30',
    reason: 'Toothache in upper right quadrant',
    price: 150,
    status: 'Completed',
    treatmentPlan: 'X-ray taken, filling applied to molar #3.',
    followUpActions: 'Monitor for any persistent pain.',
  },
  {
    id: 'con-003',
    patientId: 'pat-003',
    date: new Date(new Date().setDate(new Date().getDate() + 12)).toISOString().split('T')[0],
    time: '09:00',
    reason: 'Consultation for Root Canal',
    price: 250,
    status: 'Scheduled',
    treatmentPlan: 'Discuss procedure, risks, and benefits. Schedule root canal surgery.',
    followUpActions: 'Patient to confirm availability for surgery.',
  },
  {
    id: 'con-004',
    patientId: 'pat-004',
    date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString().split('T')[0],
    time: '11:00',
    reason: 'Cancelled by patient',
    price: 0,
    status: 'Cancelled',
    treatmentPlan: 'N/A',
    followUpActions: 'Office to call patient to reschedule.',
  },
  {
    id: 'con-005',
    patientId: 'pat-005',
    date: new Date(new Date().setDate(new Date().getDate() + 20)).toISOString().split('T')[0],
    time: '16:00',
    reason: 'Teeth Whitening Consultation',
    price: 100,
    status: 'Scheduled',
    treatmentPlan: 'Evaluate current tooth shade and discuss whitening options (in-office vs. at-home).',
    followUpActions: 'Provide patient with pricing and information packet.',
  },
];
